# Generated by Django 4.2 on 2023-05-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_newhospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newhospital',
        ),
    ]
