# Generated by Django 4.2.1 on 2023-06-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_unknownemergency'),
        ('Admin', '0015_tbl_feedback'),
        ('Rescueteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rescueinfounknown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_unknownemergency')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhospital')),
                ('rescue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rescueteam')),
            ],
        ),
    ]
