# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rescueteam', '0003_delete_tbl_rescueinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rescueinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
