# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rescueteam', '0004_tbl_rescueinfo'),
        ('Guest', '0007_tbl_userregistration'),
        ('User', '0008_initial'),
        ('Admin', '0018_tbl_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rescueinfo',
            name='emergency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_emergencyrequest'),
        ),
        migrations.AddField(
            model_name='tbl_rescueinfo',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newhospital'),
        ),
        migrations.AddField(
            model_name='tbl_rescueinfo',
            name='rescue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_rescueteam'),
        ),
    ]
