# Generated by Django 4.2 on 2023-05-15 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_newhospital'),
        ('Hospital', '0014_tbl_pyschologisttoken'),
        ('User', '0002_tbl_psychologistappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='lchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_lid', to='Hospital.tbl_pyschologist')),
                ('from_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user1', to='Guest.tbl_userregistration')),
                ('to_lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_lid', to='Hospital.tbl_pyschologist')),
                ('to_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user1', to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='cchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_cid', to='Hospital.tbl_pyschiatrist')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='Guest.tbl_userregistration')),
                ('to_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_cid', to='Hospital.tbl_pyschiatrist')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='Guest.tbl_userregistration')),
            ],
        ),
    ]
