# Generated by Django 4.2.1 on 2023-06-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rescueteam', '0003_delete_tbl_rescueinfo'),
        ('Psychologist', '0002_delete_tbl_refer'),
        ('Psychiatrist', '0002_delete_tbl_prescription'),
        ('User', '0006_delete_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lchat',
            name='from_lid',
        ),
        migrations.RemoveField(
            model_name='lchat',
            name='from_user1',
        ),
        migrations.RemoveField(
            model_name='lchat',
            name='to_lid',
        ),
        migrations.RemoveField(
            model_name='lchat',
            name='to_user1',
        ),
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_emergencyrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_psychiatristappointment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tbl_psychiatristappointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_psychologistappointment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tbl_psychologistappointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='cchat',
        ),
        migrations.DeleteModel(
            name='lchat',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_emergencyrequest',
        ),
        migrations.DeleteModel(
            name='tbl_psychiatristappointment',
        ),
        migrations.DeleteModel(
            name='tbl_psychologistappointment',
        ),
    ]
