# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0007_tbl_userregistration'),
        ('Hospital', '0014_tbl_pyschologisttoken'),
        ('User', '0007_remove_lchat_from_lid_remove_lchat_from_user1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_psychologistappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_to_date', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschologisttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_psychiatristappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_to_date', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatristtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_emergencyrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('major', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('reply', models.CharField(default='Not yet viewed', max_length=5000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='lchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_lid', to='Hospital.tbl_pyschologist')),
                ('from_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user1', to='Guest.tbl_userregistration')),
                ('to_lid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_lid', to='Hospital.tbl_pyschologist')),
                ('to_user1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user1', to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='cchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('from_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_cid', to='Hospital.tbl_pyschiatrist')),
                ('from_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_user', to='Guest.tbl_userregistration')),
                ('to_cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_cid', to='Hospital.tbl_pyschiatrist')),
                ('to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_user', to='Guest.tbl_userregistration')),
            ],
        ),
    ]
