# Generated by Django 4.2.3 on 2023-07-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0005_delete_tbl_refer'),
        ('Psychiatrist', '0005_delete_tbl_prescription'),
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_psychologistappointment',
            name='token',
        ),
        migrations.RemoveField(
            model_name='tbl_psychologistappointment',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_psychiatristappointment',
        ),
        migrations.DeleteModel(
            name='tbl_psychologistappointment',
        ),
    ]
