# Generated by Django 4.2.3 on 2023-07-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_tbl_pyschologisttoken'),
        ('Guest', '0007_tbl_userregistration'),
        ('User', '0009_remove_tbl_psychologistappointment_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_psychologistappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_to_date', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('offline_status', models.CharField(max_length=50)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschologisttoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_psychiatristappointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_to_date', models.CharField(max_length=50)),
                ('status', models.IntegerField(default=0)),
                ('offline_status', models.CharField(max_length=50)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatristtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregistration')),
            ],
        ),
    ]
