# Generated by Django 4.2 on 2023-05-12 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_tbl_psychologistappointment_and_more'),
        ('Hospital', '0014_tbl_pyschologisttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatrist')),
                ('referappointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_psychologistappointment')),
            ],
        ),
    ]
