# Generated by Django 4.2.1 on 2023-06-22 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Psychologist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_refer',
        ),
    ]
