# Generated by Django 4.2.3 on 2023-07-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hospital', '0014_tbl_pyschologisttoken'),
        ('Psychologist', '0005_delete_tbl_refer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_refer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatrist')),
            ],
        ),
    ]
