# Generated by Django 4.2 on 2023-05-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0002_tbl_psychologistappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=5000)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_psychiatristappointment')),
            ],
        ),
    ]
