# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Psychiatrist', '0002_delete_tbl_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=5000)),
            ],
        ),
    ]
