# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Psychiatrist', '0003_initial'),
        ('User', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_prescription',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_psychiatristappointment'),
        ),
    ]
