# Generated by Django 4.2 on 2023-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_tbl_subcategory_category_delete_tbl_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospitaltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitaltype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
