# Generated by Django 4.2 on 2023-05-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_rescueteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rescueteam',
        ),
    ]
