# Generated by Django 4.2 on 2023-05-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_rescueteam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rescueteam',
        ),
    ]
