# Generated by Django 4.2 on 2023-05-09 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_rescueteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rescueteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('headname', models.CharField(max_length=50)),
                ('headcontact', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='RescueteamLogo/')),
                ('password', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
