# Generated by Django 4.2.1 on 2023-06-22 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0014_tbl_pyschologisttoken'),
        ('Guest', '0006_delete_tbl_userregistration'),
        ('Admin', '0016_delete_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5000)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Guest.tbl_newhospital')),
                ('psychiatrist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.tbl_pyschiatrist')),
                ('psychologist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Hospital.tbl_pyschologist')),
            ],
        ),
    ]
