# Generated by Django 4.2 on 2023-05-09 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_tbl_pyschologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_availablepyschiatrist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.CharField(max_length=50)),
                ('to_time', models.CharField(max_length=50)),
                ('psychiatrist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatrist')),
            ],
        ),
    ]
