# Generated by Django 4.2 on 2023-05-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_tbl_availablepyschologist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_availablepyschologist',
        ),
    ]
