# Generated by Django 4.2 on 2023-05-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_delete_tbl_availablepyschologist'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_availablepsychologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('from_time', models.CharField(max_length=50)),
                ('to_time', models.CharField(max_length=50)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_pyschiatrist')),
            ],
        ),
    ]
