# Generated by Django 4.2 on 2023-05-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_tbl_availablepsychologist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_availablepsychologist',
        ),
    ]
