# Generated by Django 4.2 on 2023-05-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0013_tbl_pyschiatristtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pyschologisttoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hospital.tbl_availablepsychologist')),
            ],
        ),
    ]
